import Head from "next/head";
import Header from "../components/Header";
import Feed from "../components/Feed";
import Modal from "../components/Modal";

export default function Home() {
  return (
    <>
      <div className="bg-gray-100 h-screen overflow-y-scroll scrollbar-hide">
        <Head>
          <title>Instagram Clone Personal Project</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Header */}
        <Header />
        {/* Feed */}
        <Feed />
        {/* Modal */}
        <Modal />
      </div>
    </>
  );
}
